package server
import("encoding/json";"net/http";"strconv";"github.com/stockyard-dev/stockyard-crossroads/internal/store")
func(s *Server)handleListProfiles(w http.ResponseWriter,r *http.Request){list,_:=s.db.ListProfiles();if list==nil{list=[]store.Profile{}};writeJSON(w,200,list)}
func(s *Server)handleCreateProfile(w http.ResponseWriter,r *http.Request){var p store.Profile;json.NewDecoder(r.Body).Decode(&p);if p.Name==""||p.Slug==""{writeError(w,400,"name and slug required");return};if err:=s.db.CreateProfile(&p);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,p)}
func(s *Server)handleDeleteProfile(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteProfile(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleGetPublic(w http.ResponseWriter,r *http.Request){slug:=r.PathValue("slug");p,err:=s.db.GetProfile(slug);if err!=nil{writeError(w,404,"not found");return};links,_:=s.db.ListLinks(p.ID);if links==nil{links=[]store.Link{}};writeJSON(w,200,map[string]interface{}{"profile":p,"links":links})}
func(s *Server)handleListLinks(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);list,_:=s.db.ListLinks(id);if list==nil{list=[]store.Link{}};writeJSON(w,200,list)}
func(s *Server)handleCreateLink(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);var l store.Link;json.NewDecoder(r.Body).Decode(&l);l.ProfileID=id;l.Active=true;if l.Title==""||l.URL==""{writeError(w,400,"title and url required");return};if err:=s.db.CreateLink(&l);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,l)}
func(s *Server)handleToggleLink(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.ToggleLink(id);writeJSON(w,200,map[string]string{"status":"toggled"})}
func(s *Server)handleDeleteLink(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteLink(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleClick(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.Click(id);writeJSON(w,200,map[string]string{"status":"ok"})}
func(s *Server)handleStats(w http.ResponseWriter,r *http.Request){p,_:=s.db.CountProfiles();c,_:=s.db.TotalClicks();writeJSON(w,200,map[string]interface{}{"profiles":p,"total_clicks":c})}
