package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Crossroads</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.link-row{display:flex;align-items:center;gap:.5rem;padding:.5rem;background:var(--bg2);border:1px solid var(--bg3);margin-bottom:.3rem;font-size:.75rem}.link-slug{color:var(--rl);font-weight:600;cursor:pointer;width:100px}.link-url{flex:1;color:var(--cd);font-size:.7rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.link-clicks{color:var(--gold);font-weight:700;width:50px;text-align:right}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Crossroads</span></h1><button class="btn btn-p" onclick="showNew()">+ Shorten</button></div>
<div class="main"><div class="overview" id="ov"></div><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'never';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function load(){const[sd,ld]=await Promise.all([api('/api/stats'),api('/api/links')]);
document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.links+'</b>Links</div><div class="stat"><b>'+sd.total_clicks+'</b>Total Clicks</div>';
const links=ld.links||[];
document.getElementById('list').innerHTML=links.length?links.map(l=>'<div class="link-row"><span class="link-slug" onclick="copy(\''+esc(l.slug)+'\')">'+esc(l.slug)+'</span><span class="link-url" title="'+esc(l.url)+'">'+esc(l.url)+'</span><span class="link-clicks">'+l.clicks+'</span><span style="font-size:.6rem;color:var(--cm)">'+timeAgo(l.last_click)+'</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="del(\''+l.id+'\')">del</span></div>').join(''):'<div class="empty">No links yet. Shorten a URL to get started.</div>'}
function copy(slug){navigator.clipboard.writeText(location.origin+'/'+slug).then(()=>alert('Copied: '+location.origin+'/'+slug))}
async function del(id){await api('/api/links/'+id,{method:'DELETE'});load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Shorten URL</h2><label class="fl">URL</label><input type="text" id="nl-url" placeholder="https://example.com/very-long-url"><label class="fl">Custom Slug (optional)</label><input type="text" id="nl-slug" placeholder="my-link"><label class="fl">Title (optional)</label><input type="text" id="nl-title"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Shorten</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={url:document.getElementById('nl-url').value,slug:document.getElementById('nl-slug').value,title:document.getElementById('nl-title').value};if(!b.url){alert('URL required');return};const r=await api('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});alert('Short URL: '+location.origin+'/'+r.slug);closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
</script></body></html>`
